name = input("이름을 입력하세요: ").strip()
id  = input("학번을 입력하세요: ").strip()
major  = input("학과를 입력하세요: ").strip()
school  = input("학교를 입력하세요: ").strip()

print("\n<출력>")
print(f"이름: {name}")
print(f"학번: {id}")
print(f"학과: {major}")
print(f"학교: {school}")